### ISSUE TITLE
Renegotiation

### ISSUE THREAD

**Issue by tomas-berg** [medooze/sdpmanager-playground#2]
Why do we need renegotiation after first offer? We send sdp offer from js client and getting empty answer back. Then we send new offer from server. Why is it so?

**Comment by murillo128** [comment]
Because I am not reusing transceivers yet, as it introduces quite a lot of headaches (and potential bugs). So as new transceivers can only be added on a new offer from server, you will need to renegotiate in order to trigger it.

**Comment by tomas-berg** [comment]
Unfortunately, playground is not stable. Got:

> Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to process the bundled m= section.

Error occurs not on regular basis. Even on clear run.

**Comment by murillo128** [comment]
What browser/version?

**Comment by tomas-berg** [comment]
@murillo128 
Google Chrome Version 70.0.3521.2 (Official Build) dev (64-bit)

**Comment by murillo128** [comment]
Can you paste the local (a gist for each one would be even better) description that set in the setLocalDescription, the current local descrtiption and the remote offer?

**Comment by tomas-berg** [comment]
Client OFFER:

> v=0
↵o=- 7790156579340629438 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE 0
↵a=msid-semantic: WMS mxiqx81tSjcRTSPokHpybaUTgUigGg4x5osB
↵m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
↵c=IN IP4 0.0.0.0
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:Mzxk
↵a=ice-pwd:fGre1KS4ib8sZsefPROFbjbQ
↵a=ice-options:trickle
↵a=fingerprint:sha-256 0F:67:1F:35:9D:3A:20:8A:35:DD:B3:F6:FC:E2:99:F5:6A:EB:E8:F0:6E:6E:21:77:DD:64:63:C8:CE:A1:88:8C
↵a=setup:actpass
↵a=mid:0
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
↵a=sendonly
↵a=msid:mxiqx81tSjcRTSPokHpybaUTgUigGg4x5osB 10e34abb-4b7c-4eda-aa5f-8c4d8f23529f
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=rtcp-fb:111 transport-cc
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:104 ISAC/32000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:110 telephone-event/48000
↵a=rtpmap:112 telephone-event/32000
↵a=rtpmap:113 telephone-event/16000
↵a=rtpmap:126 telephone-event/8000
↵a=ssrc:3469128484 cname:nEKJNcOLtCxr99Zq
↵a=ssrc:3469128484 msid:mxiqx81tSjcRTSPokHpybaUTgUigGg4x5osB 10e34abb-4b7c-4eda-aa5f-8c4d8f23529f
↵a=ssrc:3469128484 mslabel:mxiqx81tSjcRTSPokHpybaUTgUigGg4x5osB
↵a=ssrc:3469128484 label:10e34abb-4b7c-4eda-aa5f-8c4d8f23529f
↵

Server ANSWER:

> v=0
↵o=- 1543319540854 1 IN IP4 127.0.0.1
↵s=semantic-sdp
↵c=IN IP4 0.0.0.0
↵t=0 0
↵a=ice-lite
↵a=msid-semantic: WMS *
↵a=group:BUNDLE 0
↵m=audio 9 UDP/TLS/RTP/SAVPF 111
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=setup:passive
↵a=mid:0
↵a=recvonly
↵a=ice-ufrag:1b2c46348c83da75
↵a=ice-pwd:0f7dcf2f3f74e720e528a02637ae70a146486280bb82050d
↵a=fingerprint:sha-256 63:6B:60:E3:86:85:35:48:49:A9:5C:C6:53:D5:A2:24:26:7F:D4:3A:84:F3:B3:80:4F:36:CB:F2:70:14:53:68
↵a=candidate:1 1 UDP 33554431 192.168.0.10 58534 typ host
↵a=rtcp-mux
↵a=rtcp-rsize
↵

Server Second OFFER:

> v=0
↵o=- 1543319541859 1 IN IP4 127.0.0.1
↵s=semantic-sdp
↵c=IN IP4 0.0.0.0
↵t=0 0
↵a=ice-lite
↵a=msid-semantic: WMS *
↵a=group:BUNDLE 0 1
↵m=audio 9 UDP/TLS/RTP/SAVPF 111
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=setup:passive
↵a=mid:0
↵a=recvonly
↵a=ice-ufrag:1b2c46348c83da75
↵a=ice-pwd:0f7dcf2f3f74e720e528a02637ae70a146486280bb82050d
↵a=fingerprint:sha-256 63:6B:60:E3:86:85:35:48:49:A9:5C:C6:53:D5:A2:24:26:7F:D4:3A:84:F3:B3:80:4F:36:CB:F2:70:14:53:68
↵a=candidate:1 1 UDP 33554431 192.168.0.10 58534 typ host
↵a=rtcp-mux
↵a=rtcp-rsize
↵m=audio 9 UDP/TLS/RTP/SAVPF 111
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=setup:passive
↵a=mid:1
↵a=msid:ea8de010-6a10-4693-b362-b6bf51d333e2 daea732e-cfb9-4852-b1ad-32e3fb55df7c
↵a=sendrecv
↵a=ice-ufrag:1b2c46348c83da75
↵a=ice-pwd:0f7dcf2f3f74e720e528a02637ae70a146486280bb82050d
↵a=fingerprint:sha-256 63:6B:60:E3:86:85:35:48:49:A9:5C:C6:53:D5:A2:24:26:7F:D4:3A:84:F3:B3:80:4F:36:CB:F2:70:14:53:68
↵a=candidate:1 1 UDP 33554431 192.168.0.10 58534 typ host
↵a=ssrc:279434614 cname:ea8de010-6a10-4693-b362-b6bf51d333e2
↵a=ssrc:279434614 msid:ea8de010-6a10-4693-b362-b6bf51d333e2 daea732e-cfb9-4852-b1ad-32e3fb55df7c
↵a=rtcp-mux
↵a=rtcp-rsize
↵

After this setLocalDescription fails with error above

**Comment by tomas-berg** [comment]
BTW, if we do it like this, for example:
```javascript
pc.addTransceiver(local_stream_track, {direction: 'sendonly'});
pc.addTransceiver('audio', { direction: 'inactive' });
```
No error on the client. Everything works, but server throws:
`[0x7f6b367e8740][1543319953.459][ERR]-AddIncomingSourceGroup media ssrc already assigned`

**Comment by tomas-berg** [comment]
Well, after adding two inactive transceivers - no more errors
